# Generated by Django 3.1.7 on 2021-03-13 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cintauser', '0002_cintauser_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cintauser',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='cintauser',
            name='image2',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
