# Generated by Django 3.1.7 on 2021-03-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cintauser', '0003_auto_20210313_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cintauser',
            old_name='name',
            new_name='username',
        ),
    ]
